jobs:
  build:
    name: ${{ matrix.os }} JDK ${{ matrix.distribution }} ${{ matrix.java }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Git checkout
      uses: actions/checkout@v1
    - continue-on-error: true
      id: setupjdk
      name: Set up JDK
      uses: actions/setup-java@v2.2.0
      with:
        distribution: ${{ matrix.distribution }}
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Build with Maven
      run: mvn verify
    strategy:
      fail-fast: false
      matrix:
        distribution:
        - temurin
        java:
        - '11'
        os:
        - ubuntu-latest
        - macOS-latest
name: Maven JVM Build
on:
  repository_dispatch:
    types: trigger-ga___maven.yml
